irecognition/irecognition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('users/', include('users.urls')),
    path('images/', include('imagerecognition.urls')),
]

irecognition/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.registration, name="registration"),
    path("logout/", views.logoutuser, name="logout"),
    path(
        "reset-password/",
        views.ResetPasswordView.as_view(),
        name="password_reset",
    ),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

irecognition/users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):
    """Custom user model manager with 'email' as a main
    field for authentication purposes."""

    def create_user(
            self,
            email: str,
            password: str = None,
            **extra_fields) -> "User":
        """Create and save a new user.

        User can be created without password to support passwordless
        authentication.

        Args:
            email (str): user email address
            password (str | None, optional): user password. Defaults to None.

        Raises:
            ValueError: in case if provided email value is None

        Returns:
            User: new user entity
        """
        if email is None:
            raise ValueError("The 'email' field must be set.")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        if password:
            user.set_password(password)

        user.save()
        return user

    def create_superuser(
            self,
            email: str,
            password: str,
            **extra_fields) -> "User":
        """Create and save a new super user.

        Args:
            email (str): superuser email address
            password (str): superuser password

        Raises:
            ValueError: in case if provided 'is_staff' value is None
            ValueError: in case if provided 'is_superuser' value is None

        Returns:
            User: new superuser entity
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    """Model representing User object.

    User model has email field set as username field. Also model has
    password field
    set as nullable to provide passwordless authentication. This
    field is present
    only to create superuser and have easy access to admin panel.
    """

    username = None
    last_name = None

    password = models.CharField(
        verbose_name="password", max_length=128, blank=False, null=True
    )
    email = models.EmailField(
        verbose_name="email address", unique=True, blank=False)

    is_active = models.BooleanField(
        verbose_name="active",
        default=True,
        help_text="Designates whether this user should be treated as active. "
        "Unselect this instead of deleting accounts.",
    )
    updated_at = models.DateTimeField(verbose_name="updated at", auto_now=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return f"{self.email}: {self.username}"

    class Meta:
        db_table = "users"
        verbose_name = "user"

    def get_full_name(self):
        raise NotImplementedError(
            "This method is not implemented, since User model\
                has no 'last_name' field."
        )

    def mark_as_active(self):
        """Activate current user."""
        self.is_active = True
        self.save()

    def update_last_login(self):
        """Update user last login time."""
        self.last_login = timezone.now()
        self.save()

irecognition/users/forms.py
from django import forms
from django.core.validators import EmailValidator


class RegistrationForm(forms.Form):
    """Registration Form"""
    email = forms.EmailField(
        label="Email",
        validators=[EmailValidator()],
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "name": "email",
                "id": "email",
                "placeholder": "Email",
            }
        ),
    )
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "type": "password",
                "name": "password",
                "id": "pswd",
                "placeholder": "Password",
            }
        ),
    )
    password2 = forms.CharField(
        label="Confirm password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "type": "password",
                "name": "password",
                "id": "pswd",
                "placeholder": "Confirm password",
            }
        ),
    )


class LoginForm(forms.Form):
    """Login Form."""
    email = forms.EmailField(
        label="Email",
        validators=[EmailValidator()],
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "name": "email",
                "id": "email",
                "placeholder": "Email",
            }
        ),
    )
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "type": "password",
                "name": "password",
                "id": "pswd",
                "placeholder": "Password",
            }
        ),
    )

irecognition/users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth import login as login_user, authenticate, logout
from django.contrib.auth.decorators import login_required

from .models import User
from .forms import (
    RegistrationForm,
    LoginForm,
)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    """Poroccess Password Reset"""
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = "users/password_reset_subject.txt"


def registration(request):
    """
    The registration function is responsible for handling
    the registration of new users.
    It does so by first checking if the request method is GET or POST.
    If it's GET, then we
    create a RegistrationForm object and render it to the user in a
    template called register.html,
    which will be created later on in this chapter. If it's POST, then
    we create another RegistrationForm object but this time with data from
    our request (request.POST). We check if that form is valid and if so we
    extract some data from our cleaned_data dictionary: email and password(s).
    We check whether both passwords match each other; otherwise,

    :param request: Get the request object
    :return: A form for registration
    """
    if request.method == "GET":
        form = RegistrationForm()
        return render(request, "users/register.html", {"form": form})

    elif request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            email = cd["email"]
            password = cd["password1"]
            password2 = cd["password2"]

            if password != password2:
                messages.warning(request, "The passwords did not match")
                return render(
                    request, "users/register.html", {"form": form}
                )

            if User.objects.filter(email=email).exists():
                messages.warning(
                    request, "Such an account is already registered")
                return redirect("users:registration")

            hashed_password = make_password(password2)

            User.objects.create_user(
                email=email,
                password=hashed_password,
            )

            messages.success(request, "You have successfully registered")
            return redirect("users:login")

        else:
            return render(
                request, "users/register.html", {"form": form}
            )

    return render(request, "users/register.html", {"form": form})


def login(request):
    """
    The login function is responsible for logging in the user.
    It checks if the request method is GET or POST, and then it
    creates a form object.
    If the request method is GET, it returns an HTML page with a
    login form to enter data into.
    If the request method is POST, it validates data from this form
    and checks whether there are any errors in them. If there are no
    errors, then we check whether all fields have been filled out
    (email and password). If they have not been filled out completely - we
    display an error message on our site that says &quot;Fill in all
    fields&quot;. Then we try to authenticate

    :param request: Get the request object
    :return: A redirect to the main page if the user is authenticated,
    """
    if request.method == "GET":
        form = LoginForm()
        return render(request, "users/login.html", {"form": form})
    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]

            if not email or not password:
                messages.warning(request, "Fill in all fields")
                return render(
                    request, "users/login.html", {"form": form}
                )
            print(f">>>: {form.data}")
            user = authenticate(request, email=email, password=password)
            print(f">>>>>> user: {user}")
            if user is not None:
                login_user(request, user)
                return redirect("mainpage:main_page")
            else:
                messages.warning(request, "Enter the correct data")
                return render(
                    request, "users/login.html", {"form": form}
                )
        else:
            return render(request, "users/login.html", {"form": form})


@login_required
def logoutuser(request):
    """
    The logoutuser function logs out the user and redirects them to
    the login page.

    :param request: Get the request object
    :return: The redirect function, which takes the user back to the login page
    """

    logout(request)
    return redirect("users:login")

irecognition/users/templates/users/login.html
{% extends "mainpage/base.html" %}
{% load static %}

{% block content %}
<section style="background-color: #535c68;">
    <br > <br >
    <div class="container pt-5">
        <div class="mx-auto card login-form" style="width: 450px">
            <div class="color-change">
            <div class="card-body">
                <form method="post" class="form-signin">
                    {% csrf_token %}
                    <img class="mb-4 mx-auto d-block logo" src="{% static 'img/logomak_logo.png' %}" alt="Logo" width="90"
                        height="90">
                    <h3 id="mid" class="text-center">Login</h3>
                    <br >
                    <div class="form-group">
                        <label for="email">Email:</label>
                        {{ form.email }}
                        <span>{{form.errors.email}}</span>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="pswd">Password:</label>
                        {{ form.password }}
                    </div>
                    <br >
                    <div class="text-center">
                        <button type="submit" class="btn btn-block btn-success">Submit</button>
                    </div>
                </form>
                <br>
                <div class="form-group text-center">
                    <a href="{% url 'users:password_reset' %}" class="ForgetPwd" value="Login">Forget Password</a>
                </div>
            </div>
        </div>
    </div>
    </div>
    <br ><br >
</section>
{% endblock %}

irecognition/users/templates/users/password_reset.html
{% extends "mainpage/base.html" %}
{% load static %}

{% block content %}
<section style="background-color: #535c68;">
    <br> <br>

    {% if messages %}
    <div>
        <br> </br>
        {% for message in messages %}
        <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <span>{{ form.non_field_errors }}</span>
    </div>
    {% endif %}

    <div class="container pt-5">
        <div class="mx-auto card login-form" style="width: 450px">
            <div class="color-change">
            <div class="card-body">
                <form method="post" class="form-signin">
                    {% csrf_token %}
                    <img class="mb-4 mx-auto d-block logo" src="{% static 'img/logomak_logo.png' %}" alt="Logo" width="90"
                        height="90">

                    <h3 id="mid" class="text-center">Reset password</h3>
                    <br>
                    <div class="form-group">
                        <div class="text-center">
                            <label for="email">Email:</label>
                            {{ form.email }}
                            <span>{{form.errors.email}}</span>
                        </div>
                    </div>
                    <br>
                    <div class="text-center">
                        <button type="submit" class="btn btn-block btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
        <br> <br>
    </div>
</section>
{% endblock %}

irecognition/users/templates/users/password_reset_complete.html
{% extends "mainpage/base.html" %}
{% block content %}
<section style="background-color: #535c68;">
    <br> <br>
    <h2 style="text-align: center; ">Password reset!</h2>
    <br><br>
</section>
{% endblock %}

irecognition/users/templates/users/password_reset_confirm.html
{% extends "mainpage/base.html" %}
{% load static %}


{% block content %}
<section style="background-color: #535c68;">
    <br> <br>
    {% if messages %}
    <div>
        {% for message in messages %}
        <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <span>{{ form.non_field_errors }}</span>
    </div>
    {% endif %}

    <div class="container pt-5">
        <div class="mx-auto card login-form" style="width: 450px">
            <div class="color-change">
            <div class="card-body">
                <form method="post" class="form-signin">
                    {% csrf_token %}
                    <img class="mb-4 mx-auto d-block logo" src="{% static 'img/logomak_logo.png' %}" alt="Logo" width="90"
                        height="90">
                    <h3 id="mid" class="mb-3 font-weight-normal">Enter new password</h3>
                    <div class="form-group">
                        {% for field in form %}
                        {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% endfor %}
                    </div>
                    <button type="submit" class="btn btn-block btn-primary">Submit</button>
                </form>
            </div>
            </div>
        </div>
        <br> <br>
    </div>
</section>

{% endblock %}

irecognition/users/templates/users/password_reset_done.html
{% extends "mainpage/base.html" %}

{% block content %}
<section style="background-color: #535c68;">
    <br> <br>
    <div style="text-align: center;">
        <h2>Password Reset Request Sent</h2>
        <p>We have sent you an email with instructions on how to reset your password.</p>
    </div>
    <br> <br>
</section>
{% endblock %}

irecognition/users/templates/users/password_reset_email.html
{% autoescape off %}
<br> <br>
<body>
    <p>Hi {{ user.email }},</p>
    <p>You have requested a password reset for your account. Click on the following link to set a new password:</p>
    <p>
        <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
            Password Reset Link
        </a>
    </p>
    <p>If you didn't request a password reset, please ignore this email.</p>
    <p>Thank you,</p>
    <p>Our Team</p>
    <br> <br>
{% endautoescape %}

irecognition/users/templates/users/register.html
{% extends "mainpage/base.html" %}
{% load static %}

{% block content %}
<section style="background-color: #535c68;">
    <br ><br >
    <div class="container pt-5">
        <div class="mx-auto card login-form" style="width: 450px">
            <div class="color-change">
            <div class="card-body">
                <img class="mb-4 mx-auto d-block logo" src="{% static 'img/logomak_logo.png' %}" alt="Logo" width="90"
                    height="90">
                <form method="post" class="form-signin">
                    {% csrf_token %}
                    <h3 id="mid" class="text-center">Registration</h3>
                    <br >
                    <div class="form-group">
                        <label for="email">Email:</label>
                        {{ form.email }}
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="pswd">Password:</label>
                        {{ form.password1 }}
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="pswd">Confirm password:</label>
                        {{ form.password2 }}
                    </div>
                    <br>
                    <div class="text-center">
                        <button type="submit" class="btn btn-block btn-success">Submit</button>
                    </div>
                </form>
                <br >
                <div class="form-group text-center">
                    <a href="{% url 'users:login' %}" class="ForgetPwd" value="Login">Login</a>
                </div>
            </div>
            </div>
        </div>
    </div>
    <br ><br >
</section> 
{% endblock %}