irecognition/imagerecognition/urls.py
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path("", views.upload_image, name="upload_image"),
    path("predicts/", views.upload_image_button, name="prediction_button"),
]

irecognition/irecognition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('users/', include('users.urls')),
    path('images/', include('imagerecognition.urls')),
]

irecognition/mainpage/urls.py
from django.urls import path

from . import views

app_name = "mainpage"

urlpatterns = [
    path("", views.main_page, name="main_page"),
    path(
        "subscribe_newsletter/",
        views.subscribe_newsletter,
        name="subscribe_newsletter"
        ),
    path(
        'contact/',
        views.contacts,
        name='contact'
        ),
]

irecognition/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.registration, name="registration"),
    path("logout/", views.logoutuser, name="logout"),
    path(
        "reset-password/",
        views.ResetPasswordView.as_view(),
        name="password_reset",
    ),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

irecognition/mainpage/models.py
from datetime import datetime, timedelta

from typing import Any
from django.db import models

from users.models import User


class UserImage(models.Manager):
    """: A custom manager for creating Image instances
    with additional statistics updates."""
    def create(self, count_successful=0, count_negative=0, **kwargs):
        user_mage = self.model(**kwargs)
        user_mage.save()

        stat = Statistics.objects.first()
        stat(
            total=stat.total + 1,
            count_successful=stat.count_successful + count_successful,
            count_negative=count_negative + count_negative,
        )

        return user_mage


class Image(models.Model):
    """Represents an image with an associated image file
    and a classification label."""
    image = models.ImageField(upload_to='images/')
    image_class = models.CharField(max_length=15, null=True)

    objects = UserImage()

    def __str__(self) -> str:
        return f"{self.image_class}"


class Model(models.Model):
    """Represents a model with a name field."""
    name = models.CharField(max_length=80, null=True)

    def __str__(self) -> str:
        return f"{self.name}"


class Statistics(models.Model):
    """Stores statistics related to successful and negative image
    classifications, along with a default developer value. Provides
    methods to calculate hours passed since a default date and update
    statistics."""
    total = models.IntegerField(default=0)
    count_successful = models.IntegerField(default=0)
    count_negative = models.IntegerField(default=0)
    developer = models.IntegerField(default=1)

    def __str__(self) -> str:
        return f"Total: {self.total}"

    @staticmethod
    def hours_passed_since_default_date():
        default_datetime = datetime.strptime(
            "2023-08-08T00:00:00", "%Y-%m-%dT%H:%M:%S")
        current_datetime = datetime.now()
        hours_passed = (
            current_datetime - default_datetime).total_seconds() / 3600
        return hours_passed

    @staticmethod
    def update_statistics():
        stat = Statistics.objects.first()
        stat.total += 1
        stat.save()

    @staticmethod
    def update_successful():
        stat = Statistics.objects.first()
        stat.count_successful += 1
        stat.save()

    @staticmethod
    def update_negative():
        stat = Statistics.objects.first()
        stat.count_negative += 1
        stat.save()


class ContactsUs(models.Model):
    """Represents user contact information, including name,
    email, subject, message, and date of submission."""
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length=2000)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}, {self.email}: {self.subject}"


class SubscribeEmailNewsletter(models.Model):
    """Stores email addresses for newsletter subscription."""
    email = models.EmailField(unique=True)

    def __str__(self) -> str:
        return f"{self.email}"

irecognition/mainpage/forms.py
from django import forms
from django.core.validators import EmailValidator

from .models import ContactsUs, SubscribeEmailNewsletter


class ContactForm(forms.ModelForm):
    """Represents a form for user contact information. It includes fields for
    the user's name, email, subject, and message. These fields have associated
    widgets that specify input types, classes, and placeholders. The form is
    linked to the ContactsUs model and includes the fields name, email,
    subject, and message."""
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'name': 'name',
                'class': 'form-control',
                'placeholder': 'Your Name'}))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'type': 'email',
                'name': 'email',
                'class': 'form-control',
                'placeholder': 'Your Email'}))
    subject = forms.CharField(
        max_length=200,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'name': 'subject',
                'class': 'form-control',
                'placeholder': 'Subject'}))
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'name': 'message',
                'class': 'form-control',
                'placeholder': 'Message', 'rows': 6}))

    class Meta:
        model = ContactsUs
        fields = ['name', 'email', 'subject', 'message']


class SubscribeEmailNewsletterForm(forms.ModelForm):
    """Represents a form for subscribing to an email newsletter. It includes
    a single field for the user's email address. The field has an email
    validator and is associated with a widget that specifies input classes,
    placeholder, and type. The form is linked to the SubscribeEmailNewsletter
    model and includes the email field."""
    email = forms.EmailField(
        validators=[EmailValidator()],
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "aria-describedby": "button-addon1",
                "name": "email",
                "type": "text",
                "placeholder": "Enter your email address",
            }
        ),
    )

    class Meta:
        model = SubscribeEmailNewsletter
        fields = ["email"]

irecognition/mainpage/views.py
from django.shortcuts import render, redirect
from django.contrib import messages as ms
from django.core.mail import send_mail

from irecognition import settings
from .forms import ContactForm, SubscribeEmailNewsletterForm
from .messages_for_visiters import thank_message, subscribe_message
from .models import Statistics


def main_page(request):
    """
    The main_page function is the main page of the website.
    It renders a template with a contact form and statistics
    about how many people have visited the site,
    and how many hours have passed since it was created.

    :param request: Get the request object
    :return: A rendered template
    """
    statistics = Statistics.objects.first()
    hours_passed = Statistics.hours_passed_since_default_date()

    context = {
        "contact_form": ContactForm(),
        "subscribe_form": SubscribeEmailNewsletterForm,
        "statistics": statistics,
        "hours_passed": hours_passed,
    }
    return render(request, 'mainpage/main.html', context=context)


def contacts(request):
    """
    The contacts function is a view that handles the contacts page.
    It renders the contact form and sends an email to the user with
    a thank you message.

    :param request: Get the request object
    :return: The contacts page with a form to send messages
    """
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            form.save()
            subject, messages = thank_message(name)
            send_mail(subject, messages, settings.EMAIL_HOST_USER, [email])
            ms.success(
                request, "Your message has been received. Thank you!"
            )
            return redirect("mainpage:main_page")
    else:
        form = ContactForm()

    return redirect("mainpage:main_page")


def subscribe_newsletter(request):
    """
    The subscribe_newsletter function is called when a user submits
    the newsletter subscription form. It takes in the request object, and if
    it's a POST request, it creates an instance of SubscribeEmailNewsletterForm
    with the data from that POST request. If that form is valid (i.e., all
    fields are filled out correctly), then we save its email field to our
    database and send an email to ourselves notifying us of this new
    subscriber.

    :param request: Get the data from the form
    :return: A redirect to the previous page
    """
    if request.method == "POST":
        form = SubscribeEmailNewsletterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            form.save()
            subject, message = subscribe_message(email)
            send_mail(subject, message, settings.EMAIL_HOST_USER, [email])
    return redirect("mainpage:main_page")

irecognition/mainpage/templates/mainpage/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>IRecognition</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  {% block head %}{% endblock %}
</head>

<body class="index-page" data-bs-spy="scroll" data-bs-target="#navmenu">
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container-fluid d-flex align-items-center justify-content-between">

      <a href="/" class="logo d-flex align-items-center me-auto me-xl-0">
        <h1>IRecognition</h1>
        <span>.</span>
      </a>

      <!-- Nav Menu -->
      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="/" class="active">Home</a></li>
          <li><a href="/#abaut">About</a></li>
          <li><a href="/#portfolio">Results</a></li>
          <li><a href="/#team">Team</a></li>
          <li><a href="/#contact">Contact</a></li>
          {% if user.is_authenticated %}
          <li><a>{{ user.email }}</a></li>
          <li><a href="{% url 'users:logout' %}" class="active">Logout</a></li>
          {% else %}
          <li><a href="{% url 'users:registration' %}" class="active">Register</a></li>
          <li><a href="{% url 'users:login' %}" class="active">Login</a></li>
          {% endif %}
        </ul>

        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav><!-- End Nav Menu -->

      <a class="btn-getstarted" href="{% url 'images:upload_image' %}">Let's try now</a> 

    </div>
  </header><!-- End Header -->

  <main id="main" style="min-height: calc(100vh - 100px);">
    {% if messages %}
    <div>
        {% for message in messages %}
        <div {% if message.tags %} class="alert-{{ message.tags }} text-center" {% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors %}
    <div class="alert alert-danger text-center" role="alert">
        <span>{{ form.non_field_errors }}</span>
    </div>
    {% endif %}
    {% block content %}
    {% endblock %}
  </main>

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-about">
          <a href="index.html" class="logo d-flex align-items-center">
            <span>IRecognition</span>
          </a>
          <p>MyCIFAR-10-Classifier: A Deep Learning Project for Image Classification" This repository contains code for training a deep learning model on the CIFAR-10 dataset and using it in a web interface for image classification.</p>
          <div class="social-links d-flex mt-4">
            <a href="https://www.linkedin.com/in/ihor-voitiuk/"><i class="bi bi-linkedin"></i></a>
            <a href="https://t.me/ihor_vt" class="telegram" target="_blank"><i class="bi bi-telegram"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contact Us</h4>
          <p>Ukraine</p>
          <p><strong>Email:</strong>
                <a aria-label="Email Ihor" href="mailto:ihorvoitiukk@gmail.com" target="_blank" data-position="top" data-tooltip="Email Ihor" class="btn-floating btn-large waves-effect waves-light blue-grey tooltipped"><i class="fa fa-envelope"></i></a><a aria-label="Email Ihor" href="mailto:ihorvoitiukk@gmail.com" class="hoverline">ihorvoitiukk@gmail.com</a>
              </p>
        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>&copy; <span>Copyright</span> <strong class="px-1"></strong> <span><a href="https://github.com/ihor-vt">Ihor Voitiuk</a></span></p>
    </div>

  </footer><!-- End Footer -->

  <!-- Scroll Top Button -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
  </div>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>
  {% block script %}
  {% endblock %}
</body>
</html>