irecognition/imagerecognition/urls.py
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path("", views.upload_image, name="upload_image"),
    path("predicts/", views.upload_image_button, name="prediction_button"),
]

irecognition/irecognition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('users/', include('users.urls')),
    path('images/', include('imagerecognition.urls')),
]

irecognition/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.registration, name="registration"),
    path("logout/", views.logoutuser, name="logout"),
    path(
        "reset-password/",
        views.ResetPasswordView.as_view(),
        name="password_reset",
    ),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

irecognition/imagerecognition/models.py
from django.db import models

# Create your models here.

irecognition/imagerecognition/forms.py
from django import forms


class UploadImageForm(forms.Form):
    """It represents a form for uploading images"""
    image = forms.ImageField()

irecognition/imagerecognition/views.py
import os
import tempfile
from django.contrib import messages
from django.shortcuts import render, redirect

from .forms import UploadImageForm
from .predict import predict_image
from mainpage.models import Statistics


def upload_image(request):
    """
    The upload_image function is responsible for handling the image upload
    form. It will save the uploaded image to a temporary file and then pass it
    to the predict_image function, which will return a prediction of what class
    the image belongs to. The prediction result is then rendered in
    an HTML page.

    :param request: Get the http request that was sent to this view
    :return: A prediction result page
    """
    if request.method == 'POST':

        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data['image']

            # Create a temporary file to save the uploaded image
            with tempfile.NamedTemporaryFile(delete=False) as temp_file:
                temp_file.write(image.read())
                temp_file_path = temp_file.name

            the_most_predicted_class, other_classes = predict_image(
                temp_file_path)

            # Read the content of the temporary file
            with open(temp_file_path, 'rb') as temp_file_content:
                content = temp_file_content.read()

            context = {
                'the_most_predicted_class': the_most_predicted_class,
                'other_classes': other_classes,
                'uploaded_image': content,
            }

            # Clean up the temporary file
            os.remove(temp_file_path)
            Statistics.update_statistics()
            return render(
                request,
                'imagerecognition/prediction_result.html',
                context,
            )
        else:
            messages.warning(
                request,
                "The file you uploaded\
                was either not an image or a corrupted image."
                )
    else:
        form = UploadImageForm()
    return render(
        request,
        'imagerecognition/image_upload.html',
        {'form': form})


def upload_image_button(request):
    if request.method == 'POST':
        if 'true_button' in request.POST:
            Statistics.update_successful()
            messages.info(
                request,
                "Thank you, we will take your application into consideration."
                )
        elif 'false_button' in request.POST:
            Statistics.update_negative()
            messages.info(
                request,
                "Thank you, we will take your application into consideration."
                )
        return redirect("images:upload_image")

    form = UploadImageForm()
    return render(
        request,
        'imagerecognition/image_upload.html',
        {'form': form})

irecognition/imagerecognition/templates/imagerecognition/image_upload.html
{% extends "mainpage/base.html" %}
{% load static %}

{% block head%}
<link href="{% static 'css/image_upload.css' %}" rel="stylesheet">
{% endblock %}
{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }} text-center" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% if form.errors %}
<div class="alert alert-danger text-center" role="alert">
    <span>{{ form.non_field_errors }}</span>
</div>
{% endif %}
{% block content %}
<br><br><br> 
<div class="wrapper">
  <div class="container">
    <h1>Upload image</h1>
    <div class="upload-container">
      <div class="border-container">
        <div class="icons fa-4x">
          <i class="fas fa-file-image" data-fa-transform="shrink-3 down-2 left-6 rotate--45"></i>
          <i class="fas fa-file-alt" data-fa-transform="shrink-2 up-4"></i>
          <i class="fas fa-file-pdf" data-fa-transform="shrink-3 down-2 right-6 rotate-45"></i>
        </div>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="file" id="file-upload" name="image">
          <!-- <p>Drag and drop files here, or 
            <input href="#" id="file-browser">browse> your computer.</p> -->
            <br><br><br>
            <input type="submit" value="Predict">
          </form>
        </div>
      </div>
      <br>
  </div>
</div>
  <br>
{% endblock %}

{% block script %}
<script src="{% static 'js/image_upload.js' %}"></script>
{% endblock %}

irecognition/imagerecognition/templates/imagerecognition/prediction_result.html
{% extends "mainpage/base.html" %}
{% load static %}
{% load base64_filters %}

{% block head %}
<link href="{% static 'css/image_upload.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<style>
    .card {
        width: 30%;
        margin: 0 auto;
    }
    .card-img-top {
        width: 100%;
        object-fit: cover;
        height: 300px;
    }
    .btn-group {
        display: flex;
        justify-content: space-between;
        margin-top: 20px;
    }
</style>
{% endblock %}

{% block content %}
<br ><br ><br > <br ><br> <br>
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <div class="card">
                <img src="data:image/jpeg;base64,{{ uploaded_image|base64encode }}" alt="Uploaded Image" class="card-img-top">
                <div class="card-body">
                    <h1 class="card-title">Prediction Result:</h1>
                    <div class="text-center">
                        <h2 class="card-subtitle mb-2 text-muted">{{ the_most_predicted_class }}</h2>
                    </div>
                    {% if other_classes %}
                        <br >
                        <p>Other classes of forecasting:</p>
                        {% for predicted_class in other_classes %}
                            <h3 class="card-subtitle mb-2 text-muted">{{predicted_class}}</h3>
                        {% endfor %}
                    {% endif %}
                    <form method="post" action="{% url 'images:prediction_button' %}">
                        {% csrf_token %}
                        <div class="btn-group">
                            <button class="btn btn-danger" name="false_button">False</button>
                            <button class="btn btn-success" name="true_button">True</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>

<script>
    var swiper = new Swiper('.swiper-container', {
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    });
</script>

{% endblock %}